export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const GET_ARCHIVETASKS_SUCCESS = 'GET_ARCHIVETASKS_SUCCESS';
export const GET_DELETEDTASKS_SUCCESS = 'GET_DELETEDTASKS_SUCCESS';